name: Release StickerApp Solution

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  SOLUTION_NAME: StickerApp

jobs:
  export:
    name: Export StickerApp Solution from DEV Environment
    runs-on: ubuntu-latest
    environment: DEV

    steps:
      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1

      # - name: who-am-i action
      #   uses: microsoft/powerplatform-actions/who-am-i@v1
      #   with:
      #     environment-url: ${{ vars.ENVIRONMENT_URL }}
      #     app-id: ${{ vars.CLIENT_ID }}
      #     tenant-id: ${{vars.TENANT_ID}}
      #     client-secret: ${{ secrets.CLIENT_SECRET }}

      - name: Create solutions directory
        run: mkdir -p "${{ github.workspace }}/solutions"

      - name: Export Solution
        uses: microsoft/powerplatform-actions/export-solution@v1
        with:
          environment-url: ${{ vars.ENVIRONMENT_URL }}
          app-id: ${{ vars.CLIENT_ID }}
          tenant-id: ${{vars.TENANT_ID}}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          solution-name: ${{ env.SOLUTION_NAME }}
          solution-output-file: "${{ github.workspace }}/solutions/${{ env.SOLUTION_NAME }}_managed.zip"
          managed: true

      - name: Export Solution (unmanaged)
        uses: microsoft/powerplatform-actions/export-solution@v1
        with:
          environment-url: ${{ vars.ENVIRONMENT_URL }}
          app-id: ${{ vars.CLIENT_ID }}
          tenant-id: ${{vars.TENANT_ID}}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          solution-name: ${{ env.SOLUTION_NAME }}
          solution-output-file: "${{ github.workspace }}/solutions/${{ env.SOLUTION_NAME }}.zip"
          managed: false

      - name: Upload Managed Solution
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.SOLUTION_NAME }}_managed"
          path: "${{ github.workspace }}/solutions/${{ env.SOLUTION_NAME }}_managed.zip"

      - name: Upload Unmanaged Solution
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.SOLUTION_NAME }}_unmanaged"
          path: "${{ github.workspace }}/solutions/${{ env.SOLUTION_NAME }}.zip"

  testing:
    name: Testing StickerApp Solution on DEV Environment
    runs-on: ubuntu-latest
    needs: export
    environment: DEV

    steps:
      - uses: actions/checkout@v4

      - name: Run the E2E test
        uses: ./.github/actions/playwright
        with:
          M365_PAGE_URL: ${{ vars.M365_PAGE_URL }}
          M365_USERNAME: ${{ secrets.M365_USERNAME }}
          M365_PASSWORD: ${{ secrets.M365_PASSWORD }}
          M365_OTP_SECRET: ${{ secrets.M365_OTP_SECRET }}
          environment: DEV
