name: Release StickerApp Solution

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  SOLUTION_NAME: StickerApp

jobs:
  export:
    name: Export StickerApp Solution from DEV Environment
    runs-on: ubuntu-latest
    environment: DEV

    steps:
      - uses: actions/checkout@v4
      
      - name: Export Solution
        uses: ./.github/actions/export
        with:
          environment-url: ${{ vars.ENVIRONMENT_URL }}
          app-id: ${{ vars.CLIENT_ID }}
          tenant-id: ${{ vars.TENANT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          solution-name: ${{ env.SOLUTION_NAME }}

  testing:
    name: Testing StickerApp Solution on DEV Environment
    runs-on: ubuntu-latest
    needs: export
    environment:
      name: DEV
      url: ${{ vars.M365_PAGE_URL }}

    steps:
      - uses: actions/checkout@v4

      - name: Run the E2E test
        uses: ./.github/actions/playwright
        with:
          M365_PAGE_URL: ${{ vars.M365_PAGE_URL }}
          M365_USERNAME: ${{ secrets.M365_USERNAME }}
          M365_PASSWORD: ${{ secrets.M365_PASSWORD }}
          M365_OTP_SECRET: ${{ secrets.M365_OTP_SECRET }}
          environment: DEV

  release:
    name: Release StickerApp Solution to PROD Environment
    runs-on: ubuntu-latest
    needs: testing
    environment: PROD

    steps:
      - uses: actions/checkout@v4

      - name: Release StickerApp Solution
        uses: ./.github/actions/release
        with:
          environment-url: ${{ vars.ENVIRONMENT_URL }}
          app-id: ${{ vars.CLIENT_ID }}
          tenant-id: ${{ vars.TENANT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          solution-name: ${{ env.SOLUTION_NAME }}
