name: Release StickerApp Solution

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  SOLUTION_NAME: StickerApp

jobs:
  export:
    runs-on: ubuntu-latest
    environment: DEV

    steps:
      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1

      - name: Export Solution
        uses: microsoft/powerplatform-actions/export-solution@v1
        with:
          environment-url: ${{ vars.ENVIRONMENT_URL }}
          app-id: ${{ vars.CLIENT_ID }}
          tenant-id: ${{secrets.TENANT_ID}}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          solution-name: ${{ env.SOLUTION_NAME }}
          solution-output-file: "${{ env.SOLUTION_NAME }}_managed.zip"
          working-directory: "solutions"
          managed: true

      - name: Export Solution (unmanaged)
        uses: microsoft/powerplatform-actions/export-solution@v1
        with:
          environment-url: ${{ vars.ENVIRONMENT_URL }}
          app-id: ${{ vars.CLIENT_ID }}
          tenant-id: ${{secrets.TENANT_ID}}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          solution-name: ${{ env.SOLUTION_NAME }}
          solution-output-file: "${{ env.SOLUTION_NAME }}.zip"
          working-directory: "solutions"
          managed: false

      - name: Upload Managed Solution
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.SOLUTION_NAME }}_managed"
          path: "solutions/${{ env.SOLUTION_NAME }}_managed.zip"

      - name: Upload Unmanaged Solution
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.SOLUTION_NAME }}_unmanaged"
          path: "solutions/${{ env.SOLUTION_NAME }}.zip"
